### ISSUE TITLE
Question about the additive attention

### ISSUE THREAD

**Issue by YiboZhao624** [YadaYuki/news-recommendation-llm#20]
Firstly, I want to extend a BIG thank you for your outstanding work, which has been incredibly helpful to me!

I still have a question regarding why the model employs additive attention instead of dot product attention. According to the famous paper *Attention Is All You Need*, both additive and dot product attention have the same computational complexity, yet dot product attention has the potential to capture more information than additive attention.

I would greatly appreciate it if someone could help clarify my confusion.

Sincerely,
Yibo

**Comment by YadaYuki** [comment]
Dot Attention and Additive Attention use the same term "Attention," but their internal calculations are entirely different.

This repository has adopted Additive Attention because there is a clear motivation to aggregate multiple vectors (let's say N) into a single vector by calculating a weighted average based on their importance. (Dot Attention does not have the function to aggregate vectors.)

For example, when there are N d-dimensional vectors, Additive Attention calculates the importance of each vector at inference time, applies a weighted average, and aggregates them into one d-dimensional vector.

This feature is very useful for news recommendation computations such as:
- Acquiring a single article vector from N word vectors in a news article.
- Acquiring a single user preference vector from N news article vectors that the user has read in the past.

Further explanation is redundant, but it is recommended to read the following papers referenced by this repository for more details:
- https://aclanthology.org/D19-1671/
- https://arxiv.org/abs/2108.09084

**Comment by YiboZhao624** [comment]
Dear YadaYuki,

Thank you so much for your thorough response! I truly appreciate you taking the time to address my inquiry. Your explanation has provided me with a clearer understanding of why the model opts for additive attention over dot product attention.

Your patience and professionalism have left a lasting impression on me, and I'm grateful for the contributions you make to the community. I will carefully consider the insights you've shared and continue to strive for learning and improvement.

Warm regards,

Yibo
